package com.march.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import com.march.quickrvlibs.RvQuickAdapter;
import com.march.quickrvlibs.inter.RvQuickInterface;
// KEEP INCLUDES END
/**
 * Entity mapped to table "DETAIL_COLLECTION".
 */
public class DetailCollection implements RvQuickInterface, java.io.Serializable, Detail {

    private String album_link;
    private String photo_src;
    private Integer width;
    private Integer height;

    // KEEP FIELDS - put your custom fields here
    public static final int TYPE_SHU = 0;
    public static final int TYPE_HENG = 1;
    // KEEP FIELDS END

    public DetailCollection() {
    }

    public DetailCollection(String photo_src) {
        this.photo_src = photo_src;
    }

    public DetailCollection(String album_link, String photo_src, Integer width, Integer height) {
        this.album_link = album_link;
        this.photo_src = photo_src;
        this.width = width;
        this.height = height;
    }

    public String getAlbum_link() {
        return album_link;
    }

    public void setAlbum_link(String album_link) {
        this.album_link = album_link;
    }

    public String getPhoto_src() {
        return photo_src;
    }

    public void setPhoto_src(String photo_src) {
        this.photo_src = photo_src;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    // KEEP METHODS - put your custom methods here
    public DetailCollection(Detail item) {
        this.album_link = item.getAlbum_link();
        this.photo_src = item.getPhoto_src();
        this.width = item.getWidth();
        this.height = item.getHeight();
    }

    @Override
    public int getRvType() {
        if (height > width)
            return 0;
        else
            return 1;
    }
    // KEEP METHODS END

}
