package com.march.reaper.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.march.reaper.imodel.bean.AlbumDetail;
import com.march.reaper.imodel.bean.AlbumItemCollection;
import com.march.reaper.imodel.bean.BeautyAlbum;
import com.march.reaper.imodel.bean.DetailCollection;
import com.march.reaper.imodel.bean.VideoFun;

import com.march.reaper.db.AlbumDetailDao;
import com.march.reaper.db.AlbumItemCollectionDao;
import com.march.reaper.db.BeautyAlbumDao;
import com.march.reaper.db.DetailCollectionDao;
import com.march.reaper.db.VideoFunDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig albumDetailDaoConfig;
    private final DaoConfig albumItemCollectionDaoConfig;
    private final DaoConfig beautyAlbumDaoConfig;
    private final DaoConfig detailCollectionDaoConfig;
    private final DaoConfig videoFunDaoConfig;

    private final AlbumDetailDao albumDetailDao;
    private final AlbumItemCollectionDao albumItemCollectionDao;
    private final BeautyAlbumDao beautyAlbumDao;
    private final DetailCollectionDao detailCollectionDao;
    private final VideoFunDao videoFunDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        albumDetailDaoConfig = daoConfigMap.get(AlbumDetailDao.class).clone();
        albumDetailDaoConfig.initIdentityScope(type);

        albumItemCollectionDaoConfig = daoConfigMap.get(AlbumItemCollectionDao.class).clone();
        albumItemCollectionDaoConfig.initIdentityScope(type);

        beautyAlbumDaoConfig = daoConfigMap.get(BeautyAlbumDao.class).clone();
        beautyAlbumDaoConfig.initIdentityScope(type);

        detailCollectionDaoConfig = daoConfigMap.get(DetailCollectionDao.class).clone();
        detailCollectionDaoConfig.initIdentityScope(type);

        videoFunDaoConfig = daoConfigMap.get(VideoFunDao.class).clone();
        videoFunDaoConfig.initIdentityScope(type);

        albumDetailDao = new AlbumDetailDao(albumDetailDaoConfig, this);
        albumItemCollectionDao = new AlbumItemCollectionDao(albumItemCollectionDaoConfig, this);
        beautyAlbumDao = new BeautyAlbumDao(beautyAlbumDaoConfig, this);
        detailCollectionDao = new DetailCollectionDao(detailCollectionDaoConfig, this);
        videoFunDao = new VideoFunDao(videoFunDaoConfig, this);

        registerDao(AlbumDetail.class, albumDetailDao);
        registerDao(AlbumItemCollection.class, albumItemCollectionDao);
        registerDao(BeautyAlbum.class, beautyAlbumDao);
        registerDao(DetailCollection.class, detailCollectionDao);
        registerDao(VideoFun.class, videoFunDao);
    }
    
    public void clear() {
        albumDetailDaoConfig.getIdentityScope().clear();
        albumItemCollectionDaoConfig.getIdentityScope().clear();
        beautyAlbumDaoConfig.getIdentityScope().clear();
        detailCollectionDaoConfig.getIdentityScope().clear();
        videoFunDaoConfig.getIdentityScope().clear();
    }

    public AlbumDetailDao getAlbumDetailDao() {
        return albumDetailDao;
    }

    public AlbumItemCollectionDao getAlbumItemCollectionDao() {
        return albumItemCollectionDao;
    }

    public BeautyAlbumDao getBeautyAlbumDao() {
        return beautyAlbumDao;
    }

    public DetailCollectionDao getDetailCollectionDao() {
        return detailCollectionDao;
    }

    public VideoFunDao getVideoFunDao() {
        return videoFunDao;
    }

}
